### ISSUE TITLE
Gravatar头像

### ISSUE THREAD

**Issue by yihui** [cosname/r-tutorial#1]
在第一个月我会给大家陆续安排一些热身任务，主要是熟悉网页环境。从易到难吧，第一件事，请没有头像的二位想办法把头像加上。

比如 @Gwill @yihui 都有头像。

**Comment by lixiaomao** [comment]
COS上的头像不太喜欢，还是自己2一下吧~~

**Comment by yihui** [comment]
嗯，很好，第一件事情顺利完成！
