### ISSUE TITLE
学习HTML

### ISSUE THREAD

**Issue by yihui** [cosname/r-tutorial#3]
按照首页的规划（ https://github.com/cosname/r-tutorial/ ），本小组成员的第一任务是学习HTML。

@Gwill 估计不用学了，那么给 @lixiaomao 和 @luyinbo 的任务是一周之内写一个简单的HTML页面，内容不限，比如简历或任意你感兴趣的内容。要求用尽量多的HTML元素，如列表、表格、标题（h1 h2之类的）、超级链接等。

教程极多，自己搜。

**Comment by luyinbo** [comment]
@yihui  师兄怎么把写好的代码直接放在这个上面。写了个初稿。有些问题不是很清楚，比如插入的图片怎么显示不出来，链接的其他网站也点不开。@lixiaomao 你有这个问题吗？

**Comment by Gwill** [comment]
在 2012年3月29日 下午5:01，陆银波 <
reply@reply.github.com

> 写道：
> 
> @yihui
>  师兄怎么把写好的代码直接放在这个上面。写了个初稿。有些问题不是很清楚，比如插入的图片怎么显示不出来，链接的其他网站也点不开。@lixiaomao  你有这个问题吗？
> 
> 你是指上传到库里吗？

如果是练习写HTML，不必上传到库里，写好直接用浏览器打开就可以浏览效果了。

**Comment by luyinbo** [comment]
我是指把我写的给你们看到。好指点指点。

**Comment by Gwill** [comment]
> 我是指把我写的给你们看到。好指点指点。

哦。那不必上传到库里，可以使用http://jsbin.com/ 写些HTML片段，javascript都删掉就。 然后可以生成分享连接，这样就可以给别人看来了。

**Comment by lixiaomao** [comment]
@luyinbo 表示还没有开始写…实习刚刚结束，这两天尽忙着check out了…唉…

**Comment by yihui** [comment]
把源代码贴到gist里：https://gist.github.com/

以后会教你们怎么用GIT和GitHub，那样会方便很多。其实你们可以随便找一个人大的师兄问问怎么安装和配置GIT，我尽快抽空整理这一块知识，在那之前，用gist就可以。

图片不妨上传到http://imgur.com ，然后复制图片地址就可以了。举个例子：

![](http://i.imgur.com/w0TcS.png)

**Comment by lixiaomao** [comment]
实在对不住大家，本不想拖到最后一天，不过这一阵子实在忙的焦头烂额……刚刚写好一个初稿……本来想做的动态一点，不过javascript没弄明白，我再学学吧。 
另外发现养成良好的设计习惯还真的不容易，我的code不仅不是文学化，简直是涂鸦化了= =
我把东西放在免费网站上了，下面是链接：http://lixiaomao.35free.net/

**Comment by yihui** [comment]
没关系，作为初学者这已经做得很好了。回头给你们说说怎么直接放GitHub上。我自己的网站就是放在GitHub上。

**Comment by luyinbo** [comment]
@yihui 师兄，我的发到gist上了。不知看到了没有。还有，可以布置下个任务了吧。

**Comment by yihui** [comment]
@lixiaomao 求炫是初学者容易追求的目标，你现在做的东西跟我八年前初学的时候差不多，例如滚动文字、框架（frameset），现在这些东西基本上已经灭绝了。R的官方网站大概是世上仅存的几个还在用古老框架技术的网站之一。不过无论如何，你现在对HTML已经有大致的了解了，我们最终的目的是避开HTML，因为它写起来太麻烦了。之所以现在让你们学习它是因为要建立将来简单的语法和现在复杂的语法之间的联系，HTML好学，问题只是敲代码太慢。

@luyinbo 我没看到你的gist，能贴个地址吗？

按照计划，下一个任务是CSS， 它和HTML紧密相连，这也体现了一个极其重要的概念：**内容和样式分离**。以后你们再慢慢体验这句话。内容与样式独立可以让我们专注于一项任务，比如你要写内容你就专心写内容，样式的问题另外单独定义；当你调整样式的时候就专注于样式，而不必到内容里去掺和。比如 @lixiaomao 现在的页面里就是样式与内容混杂在一起，可以把那些样式的定义抽出来单放在CSS文件中。

Word就是一个典型的反例（当然高级用户可以把它用好），内容与样式混杂。今天你把每个段落调整为特定格式，明天要是想换格式，就得把每个段落重新调整一遍。对CSS而言，我只需要定义段落标签`p`的样式就可以了，它会应用到每个`p`元素上。

程序设计也是如此，要不断抽象模块，能分离的尽量分离，而不要把一大堆代码扔在一个函数里，方便测试、查错。

**Comment by lixiaomao** [comment]
哦... 这样子, 我知道了~~ 弱弱滴问几句，师兄是主要觉得UCLA的那个网站不好看吗？还是功能少...那缺些什么功能呢？
还有，COS的网站的风格算的上一个非常好的样例么？

**Comment by yihui** [comment]
UCLA的网站既不太好看，也不好维护，因为是纯HTML写的。最终我们要把它建成一个好看又方便维护的网站，而且还要方便用户贡献代码，这都是后话了。

COS目前的风格不是好样例，前一版的界面还可以，这一版是迫于无奈才改的，用的基本上是Wordpress的默认主题，做了一些微调。

**Comment by luyinbo** [comment]
@yihui  https://gist.github.com/2249179

**Comment by yihui** [comment]
@luyinbo 我看了一下，意见如下：
- 编码用的是gb2312，我建议无论什么文本文件一律用UTF8编码，它也是Linux类系统的默认编码，到处通用；Windows的几百种编码对开发者来说是地狱
- 图片链接用的是本地地址，这显然是不行的，因为那个文件只存在你自己的电脑上，要让所有人都能看到的话，要么随网页上传图片（gist里面不能传）然后用相对地址，要么把图片传到其它网站，用完整的http地址（题外话说一句，别用bmp图片，它是世上最低效的图片格式；有规则几何形状的图片如R图形用png格式，否则如照片之类不规则图形的用jpeg）
- 表格布局曾经是好些年前流行的布局方式，不过现在都转向div + css布局了

**Comment by Gwill** [comment]
@luyinbo 

> @yihui https://gist.github.com/2249179

我也看了一下，意见如下：
- 不管你是看的什么材料学习的，都别再看了。。只能让你走更多的弯路。。
- 顺便搜了一个教程给你， http://www.subcide.com/articles/creating-a-css-layout-from-scratch/P1/ ，可以照这个学。。有啥不懂，再问。

**Comment by yanping** [comment]
@lixiaomao   @luyinbo  两位师弟 我就住在人大西门  找个时间我给你们讲讲github和jekyll

**Comment by yihui** [comment]
这个太好了，谢谢！两位要抓住这个机会好好了解GIT。

**Comment by luyinbo** [comment]
@yihui @Gwill  多谢！！ @yanping 我们也住西门，品一。

**Comment by yanping** [comment]
好  今晚要是你们有空的话 我去找你们  泊星地吧  电话号码悄悄发给我吧

2012/4/5 陆银波 reply@reply.github.com:

**Comment by luyinbo** [comment]
15210868606 晚上有节课。9：00以后行吗

**Comment by luyinbo** [comment]
@yanping 15210868606 晚上有节课。9：00以后行吗

**Comment by yanping** [comment]
行 我也觉得那时候合适

2012/4/5 陆银波 reply@reply.github.com:
